bilka2go:
  target: json # This is the default target
  outputs:
      oauth:
        type: bigquery
        method: oauth
        project: "{{ env_var('GCP_PROJECT_ID') }}"
        dataset: "{{ env_var('GCP_DATASET') }}"
        location: "{{ env_var('GCP_LOCATION') }}"

        # Bigquery specific configs
        job_execution_timeout_seconds: 120
        job_creation_timeout_seconds: 120
        retries: 1  # Default is 1
        job_retry_deadline_seconds: 120
        maximum_bytes_billed: 5368709120  # 5GB  
        
      keyfile:
        # Generic configs 
        type: bigquery
        method: service-account
        project: "{{ env_var('GCP_PROJECT_ID') }}"
        dataset: "{{ env_var('GCP_DATASET') }}"
        location: "{{ env_var('GCP_LOCATION') }}"
        threads: 4 

        # Bigquery specific configs
        job_execution_timeout_seconds: 120
        job_creation_timeout_seconds: 120
        retries: 1  # Default is 1
        job_retry_deadline_seconds: 120
        maximum_bytes_billed: 5368709120  # 5GB  
        
        # Service account specific configs
        keyfile: .dbt/key.json

      json:
        # Generic configs 
        type: bigquery
        method: service-account-json
        project: "{{ env_var('GCP_PROJECT_ID') }}"
        dataset: "{{ env_var('GCP_DATASET') }}"
        location: "{{ env_var('GCP_LOCATION') }}"
        threads: 4 

        # Bigquery specific configs
        job_execution_timeout_seconds: 120
        job_creation_timeout_seconds: 120
        retries: 1  # Default is 1
        job_retry_deadline_seconds: 120
        maximum_bytes_billed: 5368709120  # 5GB  
        
        # Service account specific configs
        keyfile_json:
          type: service_account
          project_id: "{{ env_var('GCP_PROJECT_ID') }}"
          private_key_id: "{{ env_var('PRIVATE_KEY_ID') }}"
          private_key: "{{ env_var('PRIVATE_KEY') }}"
          client_email: "{{ env_var('CLIENT_EMAIL') }}"
          client_id: "{{ env_var('CLIENT_ID') }}"
          auth_uri: "https://accounts.google.com/o/oauth2/auth"
          token_uri: "https://oauth2.googleapis.com/token"
          auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
          client_x509_cert_url: "{{ env_var('CLIENT_X509_CERT_URL') }}"

